#!/bin/sh
################################################
#this scripts is created by joshua at 2017-06-09
#joshau QQ:597093681
#blog:http://www.drscrewdriver.com
################################################

#init
port=3306
mysql_user="root"
mysql_pwd=""
CmdPath="/application/mysql/bin"
mysql_sock="/mysqldata/3306/mysql.sock"
#startup function
function_start_mysql()
{
    if [ ! -e "$mysql_sock" ];then
      printf "Starting MySQL...\n"
#      /bin/sh ${CmdPath}/mysqld_safe --defaults-file=/medias/mysqldata/mysqldata/my.cnf 2>&1 > /dev/null &
     /bin/sh ${CmdPath}/mysqld_safe --defaults-file=/mysqldata/3306/my.cnf 2>&1 > /dev/null &
    else
      printf "MySQL is running...\n"
      exit
    fi
}

#stop function
function_stop_mysql()
{
    if [ ! -e "$mysql_sock" ];then
       printf "MySQL is stopped...\n"
       exit
    else
       printf "Stoping MySQL...\n"
       #${CmdPath}/mysqladmin -u${mysql_user} -p${mysql_pwd} -S /medias/mysqldata/mysql/mysql.sock shutdown
	   ${CmdPath}/mysqladmin -u${mysql_user} -S /mysqldata/3306/mysql.sock shutdown
   fi
}

#restart function
function_restart_mysql()
{
    printf "Restarting MySQL...\n"
    function_stop_mysql
    sleep 2
    function_start_mysql
}

case $1 in
start)
    function_start_mysql
;;
stop)
    function_stop_mysql
;;
restart)
    function_restart_mysql
;;
*)
    printf "Usage: $0 {start|stop|restart}\n"
esac
